### ISSUE TITLE
ConditionDoesNotExistError: Unable to align metadata to expression data

### ISSUE THREAD

**Issue by zscooper** [flatironinstitute/inferelator_sc#68]
When I try to run the program, I get the error: ConditionDoesNotExistError: Unable to align metadata to expression data. I believe this is related to matching sample names in the metadata with the expression data. I know that my data has identical sets of sample IDs, and I tried again using the bsubtilis example data and received the same error. I just installed inferelator via pip in the past week, so it should be the latest version. 

Here is my script using the example data:

```
from inferelator import inferelator_workflow, inferelator_verbose_level, MPControl

inferelator_verbose_level(1)

#Setup multiprocessing so this doesn't take forever
if __name__ == '__main__':
    MPControl.set_multiprocess_engine("multiprocessing")
    MPControl.client.processes = 6
    MPControl.connect()

#Create the run
worker = inferelator_workflow(regression="bbsr", workflow="tfa") 
worker.set_network_data_flags(use_no_prior=True, use_no_gold_standard=True)
worker.set_file_paths(input_dir=".",
                      output_dir="./output_inferelator",
                      expression_matrix_file="expression.tsv",
                      tf_names_file="tf_names.tsv",
                      meta_data_file="meta_data.tsv")
worker.set_run_parameters(num_bootstraps=1, random_seed=42)

worker.run()

```

As a note, I do not have prior nor gold standard data for my project, so I need to run it with that option set.

When I run it, this is the output:
```
test % python3 inferelator_setup_test.py
2024-01-17 10:49:49 2 Inferelator parallelized using engine joblib
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/workflow_base.py:371: UserWarning: Omitting prior network data is not recommended. Performance will be poor. Use at your own risk.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/workflow_base.py:378: UserWarning: Omitting gold standard is not recommended. Output performance metrics will be meaningless. Use at your own risk
  warnings.warn(
2024-01-17 10:49:49 1 Loading TSV data file expression.tsv
2024-01-17 10:49:49 1 Loading metadata file meta_data.tsv
2024-01-17 10:49:49 1 Data loaded: InferelatorData [float64 (4218, 266), Metadata (4218, 5)] Memory: 8.98 MB
2024-01-17 10:49:49 2 Loading TF feature names from file tf_names.tsv
2024-01-17 10:49:49 1 A (266, 239) null prior has been created
2024-01-17 10:49:49 1 A (266, 239) null gold standard has been constructed
2024-01-17 10:49:49 2 Filtered prior to 239 TFs from the TF name list
2024-01-17 10:49:49 2 Creating design and response matrix from time metadata
Traceback (most recent call last):
  File "/Users/zaccooper/Documents/workspace/ENIGMA/syncom/inferelator/test/inferelator_setup_test.py", line 21, in <module>
    worker.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/tfa_workflow.py", line 164, in run
    self.startup()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/workflow_base.py", line 1291, in startup
    self.startup_finish()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/tfa_workflow.py", line 186, in startup_finish
    self.compute_common_data()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/workflows/tfa_workflow.py", line 345, in compute_common_data
    design, response, half_tau_response = drd.run(
                                          ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/preprocessing/design_response_translation.py", line 71, in run
    processor.validate_metadata(exp_data, meta_data)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/inferelator/preprocessing/metadata_parser.py", line 210, in validate_metadata
    raise ConditionDoesNotExistError("Unable to align metadata to expression data")
inferelator.preprocessing.metadata_parser.ConditionDoesNotExistError: Unable to align metadata to expression data

```

This gives the same error I receive with my own data. Is there anything I'm missing or a way to resolve this error?

**Comment by asistradition** [comment]
Most likely your expression data is genes by samples, instead of the samples x genes expected. Try adding `worker.set_file_properties(expression_matrix_columns_are_genes=False)` to your workflow. This is also required for the example bacillus data.

**Comment by zscooper** [comment]
Thanks! That's exactly the solution I needed.
